/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    QrCodeScan: typeof import('./src/components/qr-code-scan.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillSelector: typeof import('./src/components/SkillSelector.vue')['default']
    TinyRobotChat: typeof import('./src/components/tiny-robot-chat.vue')['default']
    VanIcon: typeof import('vant/es')['Icon']
  }
}
