/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const TinyModal: typeof import('@opentiny/vue-modal')['default']
  const showConfirmDialog: typeof import('vant/es')['showConfirmDialog']
  const showLoadingToast: typeof import('vant/es')['showLoadingToast']
  const showToast: typeof import('vant/es')['showToast']
}
